### ISSUE TITLE
povezave za vire 

### ISSUE THREAD

**Issue by BarbaraBone** [ul-fmf/fmfdelo#36]
Ob kliku na povezavo za literaturo na pdf-ju me pošlje na naslovnico namesto na citirano literaturo na zadnjih straneh.

**Comment by matijapretnar** [comment]
Kot sem gledal, je tu težava v kombinaciji z `\nobibliography*` iz paketa `bibentry`, ki ga uporabljamo za to, da lahko naredimo seznam literature pod programom dela. Po internetu sodeč je paket `bibentry` tako ali tako zastarel in bi ga bilo treba nadomestiti z nečim novejšim.
