### ISSUE TITLE
Podpora za PDF/A

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/fmfdelo#5]
Iz knjižnice so mi sporočili, da PDFji nekaterih študentov nimajo metapodatkov (ustrezajo pa standardu PDF/A). Ko sem poskusil prevesti uradni vzorec, sem dobil enako težavo ([primer problematičnega PDFja](https://github.com/ul-fmf/fmfdelo/files/7932491/VzorecDela.pdf)). Očitno se je z neko distribucijo TeXlive nekaj spremenilo in ne dela več (jaz imam TeXlive 2020).

Ko se to ureja, bi tudi rad naredil neko enotno in stabilno rešitev za metapodatke. Kot gledam, se pri diplomskih delih za nastavitev metapodatkov uporablja `\hypersetup`, v magistrskih delih pa se zgenerira `.xmpdata`. Zgodilo se mi je že tudi, da so morali študentje v magistrskih delih na roke napisati vsebino `.xmpdata` (torej npr. `\Title{Naslov dela}` namesto `\Title{\naslovdela}`), da se je pravilno zgeneriral PDF/A-1b. Skratka zmeda.

Mogoče bi najprej rad vedel, ali je kakšen poseben razlog, da se v enih delih uporablja en in v drugih drug pristop?

**Comment by jureslak** [comment]
Heh, zal ne. Enkrat je bil en pristop bolj enostaven, drugic pa drug
(mislim da so bile z enim take tezave, da sem obupal). Ne spomnim se vec,
kateri je bil kateri, ampak se pa spomnim, da je bilo tecno.

**Comment by matijapretnar** [comment]
Ok, hvala! Bova s @katjabercic pogledala, kaj je najenostavnejša delujoča možnost.

**Comment by matijapretnar** [comment]
Sva pogledala. Način, kot je narejeno v diplomah, deluje in je najbolj enostaven. Sva pokomentirala za zanamce, zdaj pa je treba popraviti še preostalo. Nedelujoči metapodatki v priloženi datoteki pa so težava macOS Previewa - v Acrobat Readerju se lepo prikažejo.
