### ISSUE TITLE
Rastrska pisava

### ISSUE THREAD

**Issue by hackguy25** [ul-fmf/fmfdelo#9]
Pri prevajanju predloge za magistrsko delo sem opazil, da je v PDF dokumentu uporabljena rastrska pisava namesto vektorske:
![image](https://user-images.githubusercontent.com/20540694/157014048-3ceca6a2-baa3-4faf-ae89-2a03ba4f59f4.png)
Izgled dokumenta je posledično dokaj slab na mojem zaslonu. Če zakomentiram vrstico 45: `\usepackage[T1]{fontenc}`, je v PDF uporabljena vektorska pisava, ki izgleda veliko bolje:
![image](https://user-images.githubusercontent.com/20540694/157014510-668207d8-9a01-4866-879f-ed3d86c90eb0.png)

Predlogo sem skopiral iz zip datoteke. Za urejanje uporabljam Visual Studio Code, za prevajanje pa MiKTeX na Windows 10.

**Comment by matijapretnar** [comment]
Ali lahko naložite PDF, da ga še jaz pogledam? Pri meni je namreč v obeh primerih videti vektorska pisava.

Možnost T1 je koristna zaradi zapisa besedila s šumniki. Brez nje je shranjeno npr. `ogliˇsˇce`, z njo pa `oglišče`. To se lahko vidi pri kopiranju in iskanju besedila.

**Comment by hackguy25** [comment]
Sem se poglobil v težavo in še malo pobrskal, izkazalo se je, da je težava v privzeti pisavi, ki je priložena MiKTeX-u: https://tex.stackexchange.com/questions/1291/why-are-bitmap-fonts-used-automatically
Na kratko: V MiKTeX konzoli je potrebno namestiti paket `cm-super`, ki privzete datoteke pisave Computer Modern nadomesti z vektorskimi. Predlagam, da se to zabeleži nekam v predlogo.

Predlagan popravek v odgovoru deluje kot pričakovano in omogoča tudi pravilno kopiranje besedila s šumniki. Vseeno prilagam 3 PDF datoteke: [prvotno](https://github.com/ul-fmf/fmfdelo/files/8708104/default.pdf), [brez T1](https://github.com/ul-fmf/fmfdelo/files/8708105/brez_T1.pdf) in [s popravkom](https://github.com/ul-fmf/fmfdelo/files/8708106/fixed.pdf).
